### ISSUE TITLE
Theme & config cleanup 

### ISSUE THREAD

**Issue by flynnduism** [openservicemesh/osm-www#11]
Now that we're in the post-launch phase, there's some cleanup work to be done to make sure the site is as accessible and configurable as possible for other team and community members. 

The site contents are mostly written right into the `theme/ /layouts/index.html` and ideally should be relocated into the `config.toml` file for easier editing.

**Comment by bridgetkromhout** [comment]
Closing as the theme is usable enough as-is - thanks!
