### ISSUE TITLE
blog title layout question

### ISSUE THREAD

**Issue by bridgetkromhout** [openservicemesh/osm-www#16]
Hi, @flynnduism - no matter how wide I make the viewport for a blog page like https://openservicemesh.io/blog/open-service-mesh-osm-accepted-into-cncf-as-a-sandbox-project/, the title stays in a fairly narrow left-justified column. Can we have it be closer to the width of the text below it (so a long title stacks less)? Here's an example of what I'm noticing:

![image](https://user-images.githubusercontent.com/2104453/93625764-1deb4000-f9a8-11ea-805f-068a6bbb64df.png)

**Comment by flynnduism** [comment]
This issue has been resolved - wider (normal) titles are now visible on the site.
