### ISSUE TITLE
correct footer layout

### ISSUE THREAD

**Issue by bridgetkromhout** [openservicemesh/osm-www#19]
Hi, @flynnduism - I know https://github.com/openservicemesh/osm-www/pull/18 is not ideal, so I'm filing this issue for you to correct the way the footer looks. I'd like the https://openservicemesh.io/ to look like https://smi-spec.io/ but I'm not positive how to make it that way - thanks!

**Comment by flynnduism** [comment]
Ok thanks @bridgetkromhout

I'll be working on a bunch of OSM things tomorrow, I can look at this 🖖
