### ISSUE TITLE
include community content on site front page

### ISSUE THREAD

**Issue by bridgetkromhout** [openservicemesh/osm-www#25]
As discussed in https://github.com/openservicemesh/osm-www/pull/24#issuecomment-705780125

**Comment by bridgetkromhout** [comment]
> add a community link on the main openservicemesh.io page that links out to all the community info like helm.sh 

Can we find a way to include a link (maybe in the Communication section?) to the community meetings content from https://github.com/openservicemesh/osm#community?

Three-across here instead of two-across?

![image](https://user-images.githubusercontent.com/2104453/118798716-92da8680-b863-11eb-8b1f-ec7dd0b50ff2.png)

**Comment by Santosh1176** [comment]
Hey @bridgetkromhout, I would like to work on this, if it’s still open?

**Comment by bridgetkromhout** [comment]
Thanks for the offer to work on this; however, I'm closing it now as not necessary, given that we've done fine without it.
